name: "Build portfolio"
description: "Build a portfolio from one of my repos and deploy to my GitHub page"
inputs:
  build_path:
    description: "Build output directory"
    required: true
    default: "dist"
runs:
  using: "composite"
  steps:
    - run: |
        cd portfolio
        npm i
        npm run build
    - run: mv ./portfolio/${{ inputs.build_path }} ./page/dist
    - run: |
        cd page
        git config user.email 'cgaeta@users.noreplay.github.com'
        git config user.name 'cgaeta'
        git co -b update
        git add .
        git commit -am 'update portfolio'
        # git push
        gh pr create -B main -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
