name: "Build portfolio"
description: "Build a portfolio from one of my repos and deploy to my GitHub page"
inputs:
  build_path:
    description: "Build output directory"
    required: true
    default: "dist"
runs:
  using: "composite"
  steps:
    - run: |
        cd portfolio
        npm i
        npm run build
      shell: bash
    - run: mv ./portfolio/${{ inputs.build_path }} ./page/dist
      shell: bash
    - run: |
        cd page
        git config user.email 'cgaeta@users.noreplay.github.com'
        git config user.name 'cgaeta'
        git add .
        git commit -am 'update portfolio'
        git push
      shell: bash
