name: "Build portfolio"
description: "Build a portfolio from one of my repos and deploy to my GitHub page"
inputs:
  build_path:
    description: "Build output directory"
    required: true
    default: "dist"
  token:
    description: GitHub token
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd portfolio
        npm i
        npm run build
        cd ..
        mv ./portfolio/${{ inputs.build_path }} ./page/dist
        cd page
        git config user.email 'cgaeta@users.noreplay.github.com'
        git config user.name 'cgaeta'
        git checkout -b update
        git add .
        git commit -am 'update portfolio'
        git push
        gh pr create -B main -f --H update
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
