name: "Build portfolio"
description: "Build a portfolio from one of my repos and deploy to my GitHub page"
inputs:
  build_path:
    description: "Build output directory"
    required: true
    default: "dist"
runs:
  using: "composite"
  steps:
    - run: ls -al ${{ github.action_path }}
      shell: bash
    - run: ${{ github.action_path }}/build_entrypoint.sh ${{ inputs.build_path }}
      shell: bash
