name: Build
on:
  workflow_call:
    inputs:
      repo:
        description: "Repo that I'm building from"
        type: string
        required: true
      build_path:
        description: "Build output directory"
        type: string
        required: true
        default: "dist"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm i
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cgaeta/cgaeta.github.io
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: /dist
      - run: |
          git add .
          git commit -m 'update portfolio'
          git push
